# This is a basic workflow to help you get started with Actions

name: Ganesh Ram Bit export CI

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-16.04
    env:
      BIT_TOKEN: ${{ secrets.BIT_TOKEN }}
      BIT_COLLECTION: ${{ secrets.BIT_COLLECTION }}
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    - name: Basic commands
      run: |
        lsb_release -a
        echo "Can you see this?" > file.txt
        pwd
        ls
    - name: Use Node.js
      uses: actions/setup-node@v1
      with:
        node-version: '9.4.0'
    - name: Check Node version is 9.4.0 or not
      run: node -v && npm -v
    - name: "Is repo cloned?"
      run: |
        pwd
        ls 
    # Install dependencies and build app
    - name: Install Dependencies
      run: npm install
    - name: Install bit-bin
      run: npm install bit-bin -g
    # - name: Bit tag & Bit export
    #   run: |
    #     bit config set analytics_reporting false
    #     bit config set anonymous_reporting false
    #     bit config set user.token $BIT_TOKEN
    #     bit config 
    #     bit -v && bit import && bit build
    #     bit status
    #     bit test
    #     bit tag -a
    #     bit export $BIT_COLLECTION